name = "sbale"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_id = "cda43caa-09b9-4c43-9d7e-8871bff5fc7d"
database_name = "openclaw"

[[kv_namespaces]]
binding = "RATE_KV"
id = "1684f024bb69461b9d52541ad62111b9"

# Sensitive configuration should be set via `wrangler secret put`
# Example:
#   wrangler secret put STRIPE_SECRET_KEY
#   wrangler secret put STRIPE_PUBLIC_KEY
#   wrangler secret put ADMIN_PASSWORD
